#!/bin/sh

docopy()
{
	if [ ! -f $TJSRC ]; then
		echo $TJSRC does not exist
		return
	fi
	cp $TJSRC $TJDST
}

UNAME_M=`uname -m`
SHEXT=so
if [ "`uname -s`" = "Darwin" ]; then SHEXT=dylib; fi
MYDIR=`dirname $0`

if [ "$1" = "ipp" ]; then

	TJSRC=$MYDIR/../lib/libturbojpeg-ipp.$SHEXT
	TJDST=$MYDIR/../lib/libturbojpeg.$SHEXT
	docopy

	if [ "$UNAME_M" = "x86_64" ]; then
		TJSRC=$MYDIR/../lib64/libturbojpeg-ipp.$SHEXT
		TJDST=$MYDIR/../lib64/libturbojpeg.$SHEXT
		docopy
		if [ -d $MYDIR/../lib32 ]; then
			TJSRC=$MYDIR/../lib32/libturbojpeg-ipp.$SHEXT
			TJDST=$MYDIR/../lib32/libturbojpeg.$SHEXT
			docopy
		fi
	fi

elif [ "$1" = "libjpeg" ]; then

	TJSRC=$MYDIR/../lib/libturbojpeg-libjpeg.$SHEXT
	TJDST=$MYDIR/../lib/libturbojpeg.$SHEXT
	docopy

	if [ "$UNAME_M" = "x86_64" ]; then
		TJSRC=$MYDIR/../lib64/libturbojpeg-libjpeg.$SHEXT
		TJDST=$MYDIR/../lib64/libturbojpeg.$SHEXT
		docopy
		if [ -d $MYDIR/../lib32 ]; then
			TJSRC=$MYDIR/../lib32/libturbojpeg-libjpeg.$SHEXT
			TJDST=$MYDIR/../lib32/libturbojpeg.$SHEXT
			docopy
		fi
	fi

else

	echo
	echo "USAGE: $0 < ipp | libjpeg >"
	echo
	echo "ipp = Use the accelerated version of TurboJPEG, which embeds functions from"
	echo "      the Intel(R) Integrated Performance Primitives"
	echo "libjpeg = Use the unaccelerated version of TurboJPEG, which is"
	echo "          GPL-compatible"
	echo
	exit 1

fi
